let categories =[
    {'id':'1',
    'title': 'Основные инструменты'},
    {'id':'2',
    'title': 'Фреймворки и препроцессоры css'},
    {'id':'3',
    'title': 'Библиотеки, фреймворки и пакеты js'},
    {'id':'4',
    'title': 'Фреймворки php'},
    {'id':'5',
    'title': 'Системы управления контентом'},
    {'id':'6',
    'title': 'Работа с графикой'},
    {'id':'7',
    'title': 'Безопасность пользователей в SPA'},
    {'id':'8',
    'title': 'Базы данных'},
    {'id':'9',
    'title': 'Развертывание приложений'},
];
let skills = [
    {'id':'1',
    'category_id': '1',
    'image': 'html',
    'name': 'HTML',
    'hidden_content':'Ничего'},
    {'id':'2',
    'category_id': '1',
    'image': 'css',
    'name': 'CSS',
    'hidden_content':'Ничего'},
    {'id':'3',
    'category_id': '1',
    'image': 'js',
    'name': 'JS',
    'hidden_content':'Ничего'},
    {'id':'4',
    'category_id': '1',
    'image': 'php',
    'name': 'PHP',
    'hidden_content':'Ничего'},
    {'id':'5',
    'category_id': '2',
    'image': 'botst',
    'name': 'BOOTSTRAP',
    'hidden_content':'Ничего'},
    {'id':'54',
    'category_id': '2',
    'image': 'scss',
    'name': 'SASS|SCSS',
    'hidden_content':'Ничего'},
    {'id':'6',
    'category_id': '3',
    'image': 'qr',
    'name': 'JQUERY',
    'hidden_content':'Ничего'},
    {'id':'7',
    'category_id': '3',
    'image': 'vue',
    'name': 'VUE',
    'hidden_content':'Ничего'},
    {'id':'8',
    'category_id': '3',
    'image': 'vuex',
    'name': 'VUEX',
    'hidden_content':'Ничего'},
    {'id':'9',
    'category_id': '3',
    'image': 'nuxt',
    'name': 'NUXT',
    'hidden_content':'Ничего'},
    {'id':'10',
    'category_id': '3',
    'image': 'react',
    'name': 'REACT',
    'hidden_content':'Ничего'},
    {'id':'11',
    'category_id': '3',
    'image': 'redux',
    'name': 'REDUX-TOOLKIT',
    'hidden_content':'Ничего'},
    {'id':'12',
    'category_id': '3',
    'image': 'next',
    'name': 'NEXT',
    'hidden_content':'Ничего'},
    {'id':'13',
    'category_id': '3',
    'image': 'rn',
    'name': 'REACT NATIVE',
    'hidden_content':'Ничего'},
    {'id':'14',
    'category_id': '4',
    'image': 'laravel',
    'name': 'LARAVEL',
    'hidden_content':'Версия: 7-9'},
    {'id':'15',
    'category_id': '5',
    'image': 'word',
    'name': 'WORDPRESS',
    'hidden_content':'Пытался сделать сайт через админку wordpress. Натягивал несложную верстку на wordpress.'},
    {'id':'16',
    'category_id': '5',
    'image': 'op',
    'name': 'OPENCART',
    'hidden_content':'op'},
    {'id':'1434',
    'category_id': '6',
    'image': 'ps',
    'name': 'ADOBE PHOTOSHOP',
    'hidden_content':'Для создания баннеров и т.д'},
    {'id':'14234',
    'category_id': '6',
    'image': 'figma',
    'name': 'FIGMA',
    'hidden_content':'Для создания логотипов, баннеров и т.д'},
    {'id':'17',
    'category_id': '7',
    'image': 'jwt',
    'name': 'JWT',
    'hidden_content':'Для LARAVEL https://jwt-auth.readthedocs.io/en/develop/quick-start/'},
    {'id':'18',
    'category_id': '7',
    'image': 'sanc',
    'name': 'SANCTUM',
    'hidden_content':'Ничего'},
    {'id':'19',
    'category_id': '8',
    'image': 'sql',
    'name': 'MYSQL',
    'hidden_content':'Ничего'},
    {'id':'20',
    'category_id': '9',
    'image': 'docker',
    'name': 'DOCKER',
    'hidden_content':'Ничего'},
];
export {categories, skills};